@startuml diagrama caso de uso TPI
top to bottom direction

skinparam package {
    BackgroundColor transparent
    borderColor transparente
}
' Definición de actores 
package {
    actor "Usuario" as us
    actor "Gestor de tiempo" as time
}

' Definición de casos de uso
package {
    left to right direction
    usecase "Registar nuevo retiro (1)" as UC1
    usecase "Registrar recordatorios (2 )" as UC2
    usecase "Registrar Notas pesonales (3)" as UC3
    usecase "Registrar seña (4)" as UC4
    usecase "Registrar actividades (5)" as UC5
    usecase "Registrar URL's (6)" as UC6
    usecase "Consultar reseñas (7)" as UC7
    usecase "Notificar fecha limite (8)" as UC8
}

' relaciones entre actores y casos de uso
us ---> UC1
us ---> UC2
us ---> UC3
us ---> UC4
us ---> UC5
us ---> UC6
us ---> UC7
time --> UC8
@enduml