@startuml diagrama de clases TPI.V1
' DEFINICION DE CLASES
' skinparam classAttributeFontSize 18

class Usuario {
    nroUser
    nombre
    apellido
    dni
    telefono
    domicilio
    mail
    fechaNacimiento
    retiro : Retiro
    crear ()
    mostrar ()
    calcularEdad ()
    conocerRetiro ()
}
class Retiro {
    nombre
    activades : Actividad
    descripcion
    horaInicio
    horaFin
    fechaInicio
    fechaFin
    fechaRegistro
    precio
    encargado : Encargado
    ubicacion : Ubicacion
    estado : Estado
    notas
    recordatorio : Recordatorio
    enlace : Enlace
    seña : Seña
    crear ()
    mostrar ()
    conocerActividades ()
    conocerEncargado ()
    conocerUbicacion ()
    conocerEstado ()
    conocerRecordatorio ()
    conocerEnlace ()
    registrarDiaRegistro ()
    registrarEstadoRealizado ()
    registrarEstadoReservado ()
    calcularSaldoPendiente ()
    registrarNotas ()
    notificarRecordatorio ()
    - notificarFechaFin ()
}
class Actividad {
    nroAct
    nombre
    descripcion
    horaInicio
    horaFin
    fecha 
    crear ()
    mostrar ()
    calcularDuracion ()
}

class Ubicacion {
    provincia
    ciudad
    direccion
    crear ()
    mostrar ()
}

enum Estado {
    nombre
    crear ()
    mostrar ()
    tomarNombre ()
    mostrarNombre ()
}

class Recordatorio {
    nroRec
    descripcion
    motivo
    fecha
    hora
    crear ()
    mostrar ()
}

class Enlace {
    url
    nombreWeb
    crear ()
    mostrar ()
}

class Encargado {
    tipoEncargado : TipoEncargado
    nombre
    cuil/cuit
    telefono
    mail
    crear ()
    mostrar ()
    conocerTipoEncargado ()
}

class TipoEncargado {
    tipo
    crear ()
    mostrar ()
}

class Seña {
    monto
    fecha
    medioDePago
    crear ()
    mostrar ()
}

' NOTAS CON  POSICIONAMIENTO
note left of Ubicacion::direccion
    es la combinacion de
    <b>calle y numero</b>
end note
note right of TipoEncargado
    - <b>Persona</b>
    - <b>Organizacion</b>
end note
note left of Estado
    - <b>Realizado</b>
    - <b>Reservado</b>
end note

' NOTAS CON ALIAS
note "Esta clase incluye los\nmetodos de seteo,\nlos cuales son extensivos\na las demas clases" as N1

' RELACIONES 
Usuario --> Retiro : <size: 16><b>1..*</b></size>
Retiro o-> Actividad : <size: 16><b>1..*</b></size>
Retiro -down-> Ubicacion : <size: 16><b>1</b></size>
Retiro -down-> Estado : <size: 16><b>1</b></size>
Estado .down. N1
Retiro -down-> Encargado : <size: 16><b>1</b></size>
Encargado -down-> TipoEncargado : <size: 16><b>1</b></size>
Retiro --> Recordatorio : <size: 16><b>1..*</b></size>
Retiro -left-> Enlace : <size: 16><b>0..*</b></size>
Retiro -right-> Seña : <size: 16><b>0..1</b></size>

@enduml