@startuml diagrama caso de uso TPI
' CONFIGURACION DEL DIAGRAMA
top to bottom direction
skinparam package {
    BackgroundColor transparent
    borderColor transparente
}
' Definición de actores 
package {
    actor "Usuario" as us
    actor "Gestor de tiempo" as time
}

' Definición de casos de uso
package {
    left to right direction
    usecase "Registar nuevo retiro (1)" as UC1
    usecase "Modificar retiro (4)" as UC4
    usecase "Registrar encargado (3)" as UC3
    usecase "Registrar ubicacion (2)" as UC2

    UC1 <.. UC2 : <<extend>>
    UC1 <.. UC3 : <<extend>>
    UC1 <.. UC4 : <<extend>>
}

package {
    left to right direction
    usecase "Registrar fin de retiro (5)" as UC5
    usecase "Consultar retiros (6)" as UC6
    usecase "Cancelar retiro (7)" as UC7
    usecase "Registrar recordatorios (8)" as UC8
    usecase "Registrar Notas pesonales (9)" as UC9
    usecase "Registrar pago (10)" as UC10
    usecase "Consultar reseñas (11)" as UC11
    usecase "Notificar fecha limite (12)" as UC12
    usecase "Notificar recordatorios personalizados (13)" as UC13
}

' relaciones entre actores y casos de uso
us ---> UC1
us ---> UC5
us ---> UC6
us ---> UC7
us ---> UC8
us ---> UC9
us ---> UC10
us ---> UC11

time ---> UC12
time --> UC13

@enduml